apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhods-config
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: rhods-groups-config
      labels:
        app: jupyterhub
        opendatahub.io/modified: 'false'
    data:
      admin_groups: rhods-admins
      allowed_groups: rhods-users
parameters: []


